#TODO: Provide instructions for modpack devs.
---
ModPackConfigName: null
ModPackConfigVersion: 0
ShowOTGWorldCreationMenu: true
version: 1
WorldName: "DregoraRL"
Overworld:
  PresetName: "DregoraRL"
  DimensionId: 0
  ShowInWorldCreationGUI: true
  LowestSupportedModPackConfigVersion: 0
  RemoveOnUpdate: false
  Seed: ""
  GameType: "Survival"
  BonusChest: false
  AllowCheats: false
  WorldBorderRadiusInChunks: 0
  PregeneratorRadiusInChunks: 0
  Settings:
    DimensionPortalMaterials:
    - "QUARK:BASALT:1"
    - "QUARK:WORLD_STONE_CARVED:3"
    - "LYCANITESMOBS:ASHENSTONEPILLAR"
    PortalColor: "black"
    PortalParticleType: "depthsuspend"
    PortalMobType: ""
    PortalMobSpawnChance: 0
    IsOTGPlus: true
    DimensionBelow: "Underneath"
    DimensionAbove: ""
    DimensionBelowHeight: 0
    DimensionAboveHeight: 256
    TeleportToSpawnOnly: false
    WelcomeMessage: ""
    DepartMessage: ""
    HasSkyLight: true
    IsSurfaceWorld: true
    CanRespawnHere: true
    DoesWaterVaporize: false
    DoesXZShowFog: false
    UseCustomFogColor: true
    FogColorRed: 0.90586
    FogColorGreen: 0.67809
    FogColorBlue: 0.52605
    IsSkyColored: true
    CloudHeight: 220
    CanDoLightning: true
    CanDoRainSnowIce: true
    IsNightWorld: false
    VoidFogYFactor: 0.03125
    GravityFactor: 0.08
    ShouldMapSpin: false
    CanDropChunk: true
    RespawnDimension: 0
    MovementFactor: 1
    ItemsToAddOnJoinDimension: ""
    ItemsToRemoveOnJoinDimension: ""
    ItemsToAddOnLeaveDimension: ""
    ItemsToRemoveOnLeaveDimension: ""
    ItemsToAddOnRespawn: ""
    SpawnPointSet: true
    SpawnPointX: 0
    SpawnPointY: 0
    SpawnPointZ: 0
    PlayersCanBreakBlocks: true
    ExplosionsCanBreakBlocks: true
    PlayersCanPlaceBlocks: true
  GameRules:
    CommandBlockOutput: true
    DisableElytraMovementCheck: true
    DoDaylightCycle: true
    DoEntityDrops: true
    DoFireTick: true
    DoLimitedCrafting: false
    DoMobLoot: true
    DoMobSpawning: true
    DoTileDrops: true
    DoWeatherCycle: true
    GameLoopFunction: true
    KeepInventory: false
    LogAdminCommands: true
    MaxCommandChainLength: 65536
    MaxEntityCramming: 24
    MobGriefing: true
    NaturalRegeneration: true
    RandomTickSpeed: 3
    ReducedDebugInfo: false
    SendCommandFeedback: true
    ShowDeathMessages: true
    SpawnRadius: 6000
    SpectatorsGenerateChunks: true
Dimensions:
- PresetName: "Underneath"
  DimensionId: 3
  ShowInWorldCreationGUI: true
  LowestSupportedModPackConfigVersion: 0
  RemoveOnUpdate: false
  Seed: "382688963082543104"
  GameType: "Survival"
  BonusChest: false
  AllowCheats: false
  WorldBorderRadiusInChunks: 0
  PregeneratorRadiusInChunks: 0
  Settings:
    DimensionPortalMaterials:
    - "SRPARASITES:PARASITESTAIN"
    - "SRPARASITES:PARASITERUBBLEDENSE:1"
    - "SRPARASITES:PARASITESTAIN:1"
    PortalColor: "darkred"
    PortalParticleType: "townaura"
    PortalMobType: ""
    PortalMobSpawnChance: 0
    IsOTGPlus: true
    DimensionBelow: "Underneath"
    DimensionAbove: ""
    DimensionBelowHeight: 0
    DimensionAboveHeight: 256
    TeleportToSpawnOnly: false
    WelcomeMessage: ""
    DepartMessage: ""
    HasSkyLight: false
    IsSurfaceWorld: false
    CanRespawnHere: true
    DoesWaterVaporize: false
    DoesXZShowFog: true
    UseCustomFogColor: true
    FogColorRed: 0.4
    FogColorGreen: 0.08
    FogColorBlue: 0.08
    IsSkyColored: true
    CloudHeight: 500
    CanDoLightning: true
    CanDoRainSnowIce: true
    IsNightWorld: true
    VoidFogYFactor: 0.8
    GravityFactor: 0.07
    ShouldMapSpin: false
    CanDropChunk: true
    RespawnDimension: 3
    MovementFactor: 1
    ItemsToAddOnJoinDimension: ""
    ItemsToRemoveOnJoinDimension: ""
    ItemsToAddOnLeaveDimension: ""
    ItemsToRemoveOnLeaveDimension: ""
    ItemsToAddOnRespawn: ""
    SpawnPointSet: true
    SpawnPointX: 0
    SpawnPointY: 260
    SpawnPointZ: 0
    PlayersCanBreakBlocks: true
    ExplosionsCanBreakBlocks: true
    PlayersCanPlaceBlocks: true
  GameRules:
    CommandBlockOutput: true
    DisableElytraMovementCheck: true
    DoDaylightCycle: false
    DoEntityDrops: true
    DoFireTick: true
    DoLimitedCrafting: false
    DoMobLoot: true
    DoMobSpawning: true
    DoTileDrops: true
    DoWeatherCycle: false
    GameLoopFunction: true
    KeepInventory: false
    LogAdminCommands: true
    MaxCommandChainLength: 65536
    MaxEntityCramming: 24
    MobGriefing: true
    NaturalRegeneration: true
    RandomTickSpeed: 3
    ReducedDebugInfo: false
    SendCommandFeedback: true
    ShowDeathMessages: true
    SpawnRadius: 5000
    SpectatorsGenerateChunks: true